// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB167_0oezBuSruol-GypBmsqfzn8nsHNM',
    appId: '1:458923365828:web:a522f6b3ccf1b6650ec091',
    messagingSenderId: '458923365828',
    projectId: 'jangalekat',
    authDomain: 'jangalekat.firebaseapp.com',
    storageBucket: 'jangalekat.firebasestorage.app',
    measurementId: 'G-8ETS1D4620',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnT_t2c3lgBY_QivOBoRbgFUqCRdeKmO0',
    appId: '1:458923365828:android:8c102c3802955f2b0ec091',
    messagingSenderId: '458923365828',
    projectId: 'jangalekat',
    storageBucket: 'jangalekat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNfWvAMjE9np2Y5oOPQSIwKIwfLdvIMM',
    appId: '1:458923365828:ios:da50f53b3579aef80ec091',
    messagingSenderId: '458923365828',
    projectId: 'jangalekat',
    storageBucket: 'jangalekat.firebasestorage.app',
    iosBundleId: 'com.jangalekat.jangalekatMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNfWvAMjE9np2Y5oOPQSIwKIwfLdvIMM',
    appId: '1:458923365828:ios:da50f53b3579aef80ec091',
    messagingSenderId: '458923365828',
    projectId: 'jangalekat',
    storageBucket: 'jangalekat.firebasestorage.app',
    iosBundleId: 'com.jangalekat.jangalekatMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB167_0oezBuSruol-GypBmsqfzn8nsHNM',
    appId: '1:458923365828:web:3293c9674b7ebbd80ec091',
    messagingSenderId: '458923365828',
    projectId: 'jangalekat',
    authDomain: 'jangalekat.firebaseapp.com',
    storageBucket: 'jangalekat.firebasestorage.app',
    measurementId: 'G-28XFD3EQNJ',
  );
}
